// import { cookies, headers } from 'next/headers';
// import { END } from 'redux-saga';

// import Providers from '@/store/Providers';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  // const cookieStore = await cookies();
  // const cookieString = cookieStore.getAll()
  //   .map(({ name, value }) => `${name}=${value}`)
  //   .join('; ');

  // const localeCookie = cookieStore.get('i18next')?.value ?? 'ko-KR';
  // const localeCookie = cookieStore.get('i18next') ?? 'ko-KR';
  // const headersList = await headers();
  // const userAgent = headersList.get('user-agent') ?? '';
  // const isMobile = /mobile|android|iphone|ipad/i.test(userAgent);

  return (
    <html
      lang="ko-KR"
      // className={}
    >
      <body>
        {children}
        {/* <Providers preloadedState={{}}>
        </Providers> */}
      </body>
    </html>
  );
}

export default RootLayout;
